apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-svc
  labels:
     app: myjavaapp-pod
     version: 2.7.1
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    protocol: TCP
  selector:
     app: myjavaapp-pod
     version: 2.7.1
